<?php

namespace Database\Seeders;

use App\Models\InternalRemark;
use App\Models\Property;
use App\Models\PropertyMedia;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        $properties = [
            [
                'title' => 'Cliffside Beachfront Estate at Thottada',
                'slug' => 'cliffside-beachfront-estate-thottada',
                'purpose' => 'sale',
                'type' => 'house',
                'price' => 32500000.00,
                'price_basis' => 'total',
                'negotiable' => true,
                'land_area' => 38.5,
                'land_area_unit' => 'cent',
                'building_area_sqft' => 4200.00,
                'bedrooms' => 5,
                'bathrooms' => 5,
                'amenities' => ['Private Beach Access', 'Infinity Pool', 'Solar Power Backup', 'Landscaped Courtyard', 'Borewell & Open Well'],
                'pros' => ['Panoramic Arabian Sea view', 'High tourism / boutique homestay potential', 'Clear single-owner title deed since 1982'],
                'cons' => ['Coastal Regulation Zone (CRZ) constraints for new exterior expansion', '12-foot access road requires cautious driving for heavy vehicles'],
                'description' => 'Spectacular seaside luxury estate nestled along the serene cliffs of Thottada beach. Traditional Kerala architecture fused with contemporary Scandinavian interiors. Features double-height living areas and open sit-outs overlooking the ocean.',
                'locality' => 'Thottada',
                'district' => 'Kannur',
                'address_line' => 'House 4/218, Beach Road, Thottada, Kannur 670007',
                'latitude' => 11.8239,
                'longitude' => 75.4190,
                'virtual_tour_url' => 'https://my.matterport.com/show/?m=sample-thottada-estate',
                'rera_number' => 'K-RERA/PRJ/KAN/042/2024',
                'land_classification' => 'Residential / Garden Land (Purayidam)',
                'status' => 'available',
                'is_published' => true,
                'is_featured' => true,
                'view_count' => 342,
                'meta_title' => 'Beachfront Luxury Estate for Sale in Thottada, Kannur | KARMA',
                'meta_description' => 'Spectacular 5BHK seaside luxury estate on 38.5 cents in Thottada with private beach access and infinity pool.',
                'owner_name' => 'Capt. C. P. Somanathan (Retd.)',
                'owner_phone' => '+971 50 882 1928',
                'owner_email' => 'somanathan.c@gmail.com',
                'owner_notes' => 'Settled in Dubai. Primary title deed in SBI Locker, South Bazar. Authorized KARMA for exclusive representation.',
                'remark' => 'Owner resides in Dubai. Wants token advance of 15% before initiating sale agreement. Valuation is solid; adjacent property recently traded at 8.2 Lakhs/cent.',
            ],
            [
                'title' => 'Prime Commercial Corner Plot on NH-66 Talap',
                'slug' => 'prime-commercial-corner-plot-talap',
                'purpose' => 'sale',
                'type' => 'land',
                'price' => 45000000.00,
                'price_basis' => 'total',
                'negotiable' => false,
                'land_area' => 25.0,
                'land_area_unit' => 'cent',
                'building_area_sqft' => null,
                'bedrooms' => null,
                'bathrooms' => null,
                'amenities' => ['3-Phase Electricity', 'Wide Highway Frontage (65 ft)', 'Water Connection', 'Tarred Road Frontage'],
                'pros' => ['Direct frontage on NH-66 highway expansion', 'Ideal for diagnostic center, car showroom or corporate bank branch'],
                'cons' => ['High upfront capital required', 'Commercial tax bracket applies'],
                'description' => 'Highly coveted commercial corner land situated at the junction of Talap and the newly widened NH-66 highway. Immediate commercial conversion permit in hand.',
                'locality' => 'Talap',
                'district' => 'Kannur',
                'address_line' => 'Opposite AKG Memorial Hospital, Talap, Kannur 670002',
                'latitude' => 11.8833,
                'longitude' => 75.3667,
                'virtual_tour_url' => null,
                'rera_number' => null,
                'land_classification' => 'Commercial (Dry Land / Nanja nilam converted)',
                'status' => 'available',
                'is_published' => true,
                'is_featured' => true,
                'view_count' => 580,
                'meta_title' => '25 Cents Commercial Highway Plot in Talap, Kannur | KARMA',
                'meta_description' => 'Prime commercial land on NH-66 Talap junction with 65ft road frontage. Ready for hospital, showroom or bank.',
                'owner_name' => 'K. V. Govindan Kutty & Sons',
                'owner_phone' => '+91 94470 11223',
                'owner_email' => 'govindankutty@kvgtrust.org',
                'owner_notes' => 'Family business trust. All tax receipts up to 2026 cleared. No legal disputes.',
                'remark' => 'Title verified by Adv. Sreedharan. No encumbrances. Owner open to joint development with reputable builder.',
            ],
            [
                'title' => 'Skyline View 3BHK Penthouse in Pallikkunnu',
                'slug' => 'skyline-view-3bhk-penthouse-pallikkunnu',
                'purpose' => 'sale',
                'type' => 'flat',
                'price' => 11800000.00,
                'price_basis' => 'total',
                'negotiable' => true,
                'land_area' => null,
                'land_area_unit' => 'sqft',
                'building_area_sqft' => 2350.00,
                'bedrooms' => 3,
                'bathrooms' => 3,
                'amenities' => ['Covered Reserved Parking (2 cars)', 'Clubhouse & Gymnasium', '24/7 Security & CCTV', 'Automatic Generator Backup', 'Rooftop Party Area'],
                'pros' => ['Top-floor unit with unhindered city views', 'High rental yield (approx ₹38,000/month)', 'Reputed builder with A-grade occupancy certificate'],
                'cons' => ['Monthly maintenance ₹4,500', 'Pets require association pre-approval'],
                'description' => 'Ultra-spacious penthouse featuring Italian marble flooring, modular German kitchen with built-in appliances, and a private wraparound balcony looking over the lush canopy of Pallikkunnu.',
                'locality' => 'Pallikkunnu',
                'district' => 'Kannur',
                'address_line' => 'Flat 11B, Skyline Oasis, Near Civil Station, Pallikkunnu, Kannur 670004',
                'latitude' => 11.8900,
                'longitude' => 75.3600,
                'virtual_tour_url' => 'https://my.matterport.com/show/?m=sample-skyline-penthouse',
                'rera_number' => 'K-RERA/PRJ/KAN/019/2021',
                'land_classification' => 'Residential Flat',
                'status' => 'available',
                'is_published' => true,
                'is_featured' => true,
                'view_count' => 219,
                'meta_title' => 'Luxury 3BHK Penthouse for Sale in Pallikkunnu, Kannur | KARMA',
                'meta_description' => '2350 sq.ft penthouse with skyline views, 2 car parking, and Italian marble interiors near Civil Station.',
                'owner_name' => 'Pradeep Kumar Nair',
                'owner_phone' => '+91 98450 77665',
                'owner_email' => 'pradeep.nair@infosys.com',
                'owner_notes' => 'Bangalore tech VP. Wants prompt registration within 45 days.',
                'remark' => 'Client relocated to Bangalore. Price can be negotiated down to ₹1.12 Cr for an all-cash settlement within 30 days.',
            ],
            [
                'title' => 'Airport Logistics Warehouse & Yard in Mattannur',
                'slug' => 'airport-logistics-warehouse-mattannur',
                'purpose' => 'lease',
                'type' => 'warehouse',
                'price' => 220000.00,
                'price_basis' => 'per_month',
                'negotiable' => true,
                'land_area' => 60.0,
                'land_area_unit' => 'cent',
                'building_area_sqft' => 14000.00,
                'bedrooms' => null,
                'bathrooms' => 4,
                'amenities' => ['Container Truck Turning Radius', 'Insulated PEB Structure', 'Loading Docks (4 bays)', 'Heavy-duty Epoxy Flooring', 'Fire Hydrant System'],
                'pros' => ['Only 4.5 km from Kannur International Airport (CNN) cargo gate', 'Clear 9-meter eave height for vertical racking', 'Ready for immediate handover'],
                'cons' => ['Minimum 3-year lock-in period required', 'Security deposit equivalent to 6 months rent'],
                'description' => 'State-of-the-art logistics hub built to Grade-A specifications. Ideal for courier hubs, e-commerce fulfillment, cold storage conversion, or pharmaceutical distribution.',
                'locality' => 'Mattannur',
                'district' => 'Kannur',
                'address_line' => 'Plot 8B, KINFRA Industrial Park Link Road, Mattannur 670702',
                'latitude' => 11.9300,
                'longitude' => 75.5700,
                'virtual_tour_url' => null,
                'rera_number' => null,
                'land_classification' => 'Industrial / Commercial',
                'status' => 'available',
                'is_published' => true,
                'is_featured' => false,
                'view_count' => 145,
                'meta_title' => '14,000 Sq.Ft Warehouse for Lease near Kannur Airport | KARMA',
                'meta_description' => 'Grade-A logistics warehouse with 4 loading bays and container turning radius just 4.5 km from Kannur Airport.',
                'owner_name' => 'K. M. Haridas',
                'owner_phone' => '+91 94473 88990',
                'owner_email' => 'haridas.logistics@gmail.com',
                'owner_notes' => 'Industrial warehouse owner. Open to 3 to 9 year lease contracts.',
                'remark' => 'Currently being scouted by Blue Dart. If corporate lease is agreed, KARMA brokerage is 1 month rent.',
            ],
            [
                'title' => 'Heritage Nalukettu Villa on 50 Cents in Taliparamba',
                'slug' => 'heritage-nalukettu-villa-taliparamba',
                'purpose' => 'sale',
                'type' => 'house',
                'price' => 28000000.00,
                'price_basis' => 'total',
                'negotiable' => true,
                'land_area' => 50.0,
                'land_area_unit' => 'cent',
                'building_area_sqft' => 3800.00,
                'bedrooms' => 4,
                'bathrooms' => 4,
                'amenities' => ['Traditional Nadumuttam (Central Courtyard)', 'Teakwood Woodwork', 'Organic Fruit Orchard', 'Perennial Natural Pond', 'Outhouse / Servant Quarters'],
                'pros' => ['Authentic antique wood carvings and brass fittings', 'Abundant natural water source even during peak summer', 'Peaceful, green neighborhood near Rajarajeshwara Temple'],
                'cons' => ['Periodic wood polishing maintenance needed', 'Distance from Kannur city center is 22 km'],
                'description' => 'A restored 75-year-old architectural masterpiece featuring genuine Anjili and Teak timber, traditional copper roof ridge details, and an enchanting central open-to-sky courtyard surrounded by 50 cents of mature coconut, mango, and areca palms.',
                'locality' => 'Taliparamba',
                'district' => 'Kannur',
                'address_line' => 'Trichambaram Road, Near Temple, Taliparamba 670141',
                'latitude' => 12.0400,
                'longitude' => 75.3500,
                'virtual_tour_url' => null,
                'rera_number' => null,
                'land_classification' => 'Residential Garden Land',
                'status' => 'available',
                'is_published' => true,
                'is_featured' => false,
                'view_count' => 410,
                'meta_title' => 'Heritage Nalukettu Villa on 50 Cents in Taliparamba | KARMA',
                'meta_description' => 'Restored 4BHK traditional Kerala nalukettu home with courtyard, natural pond, and organic orchard.',
                'owner_name' => 'Dr. K. N. Namboodiri',
                'owner_phone' => '+91 94460 33445',
                'owner_email' => 'namboodiri.kn@aims.org',
                'owner_notes' => 'Ayurvedic doctor family. Clear partition deed.',
                'remark' => 'Family trust property; all 4 legal heirs have signed power of attorney authorizing sale through KARMA.',
            ],
            [
                'title' => 'Gated Community Residential Plot in Chalad',
                'slug' => 'gated-community-residential-plot-chalad',
                'purpose' => 'sale',
                'type' => 'land',
                'price' => 6500000.00,
                'price_basis' => 'total',
                'negotiable' => false,
                'land_area' => 10.0,
                'land_area_unit' => 'cent',
                'building_area_sqft' => null,
                'bedrooms' => null,
                'bathrooms' => null,
                'amenities' => ['Compound Wall & Gate', 'Tarred Internal 20ft Road', 'Street Lighting', 'KWA Water Line'],
                'pros' => ['Square-shaped plot with excellent vaastu alignment', 'Walking distance to English medium school and supermarket'],
                'cons' => ['Fixed price per cent of ₹6.5 Lakhs'],
                'description' => 'Perfect square plot in an exclusive residential enclave in Chalad. Completely compound-walled with automated entry barrier, lush landscaping, and ready water/electric connections.',
                'locality' => 'Chalad',
                'district' => 'Kannur',
                'address_line' => 'Green Valley Enclave, Near Alavil Bridge, Chalad, Kannur 670014',
                'latitude' => 11.8850,
                'longitude' => 75.3550,
                'virtual_tour_url' => null,
                'rera_number' => null,
                'land_classification' => 'Residential (Dry Land)',
                'status' => 'available',
                'is_published' => true,
                'is_featured' => false,
                'view_count' => 180,
                'meta_title' => '10 Cents Residential Plot in Chalad, Kannur | KARMA',
                'meta_description' => 'Gated community square plot with compound wall, tarred road, and KWA water in Chalad.',
                'owner_name' => 'T. P. Muralidharan',
                'owner_phone' => '+91 98951 22334',
                'owner_email' => 'muralidharan.tp@ksebltd.in',
                'owner_notes' => 'Retired KSEB engineer.',
                'remark' => 'Immediate registration feasible. Clear EC for 30 years obtained.',
            ],
            [
                'title' => 'National Highway Commercial Showroom Space in Chovva',
                'slug' => 'national-highway-commercial-showroom-chovva',
                'purpose' => 'rent',
                'type' => 'commercial',
                'price' => 85000.00,
                'price_basis' => 'per_month',
                'negotiable' => true,
                'land_area' => null,
                'land_area_unit' => 'sqft',
                'building_area_sqft' => 1850.00,
                'bedrooms' => null,
                'bathrooms' => 2,
                'amenities' => ['Toughened Glass Elevation', 'Ample Customer Parking', 'Lift Access', 'Backup Generator'],
                'pros' => ['High footfall area next to railway overbridge', 'Maximum visibility for retail brands'],
                'cons' => ['Heavy peak hour traffic on main road'],
                'description' => 'Ground floor corner showroom with full glass frontage facing the highway. Ready for immediate interior fit-out by lifestyle brands, electronics, or clinics.',
                'locality' => 'Chovva',
                'district' => 'Kannur',
                'address_line' => 'Ground Floor, Royal Plaza, Chovva Junction, Kannur 670006',
                'latitude' => 11.8600,
                'longitude' => 75.3950,
                'virtual_tour_url' => null,
                'rera_number' => null,
                'land_classification' => 'Commercial',
                'status' => 'available',
                'is_published' => true,
                'is_featured' => false,
                'view_count' => 98,
                'meta_title' => 'Ground Floor Commercial Showroom for Rent in Chovva, Kannur',
                'meta_description' => '1850 sq.ft prime commercial space with glass frontage and parking on NH Chovva Junction.',
                'owner_name' => 'Royal Builders Kannur',
                'owner_phone' => '+91 94471 99001',
                'owner_email' => 'leasing@royalbuilderskannur.com',
                'owner_notes' => 'Direct developer inventory.',
                'remark' => 'Rent negotiable to ₹78k for long term 5+ year lease agreement.',
            ],
            [
                'title' => 'Coconut Grove Island Plot in Dharmadam',
                'slug' => 'coconut-grove-island-plot-dharmadam',
                'purpose' => 'sale',
                'type' => 'land',
                'price' => 16000000.00,
                'price_basis' => 'total',
                'negotiable' => true,
                'land_area' => 32.0,
                'land_area_unit' => 'cent',
                'building_area_sqft' => null,
                'bedrooms' => null,
                'bathrooms' => null,
                'amenities' => ['Riverfront Boundary', 'Private Boat Jetty Berth', 'Rich Alluvial Soil', 'Fenced Perimeter'],
                'pros' => ['Picturesque river frontage flowing into Dharmadam island estuary', 'Superb setting for boutique eco-resort or wellness retreat'],
                'cons' => ['Requires embankment retaining wall reinforcement along 40ft river edge'],
                'description' => 'Serene parcel of fertile riverbank land studded with 45 bearing coconut trees. Quiet natural sanctuary with cool breeze year-round.',
                'locality' => 'Dharmadam',
                'district' => 'Kannur',
                'address_line' => 'River View Point, Near Dharmadam Island Walkway 670106',
                'latitude' => 11.7770,
                'longitude' => 75.4670,
                'virtual_tour_url' => null,
                'rera_number' => null,
                'land_classification' => 'Agricultural / Garden Land',
                'status' => 'available',
                'is_published' => true,
                'is_featured' => false,
                'view_count' => 310,
                'meta_title' => '32 Cents Waterfront Coconut Grove Land in Dharmadam | KARMA',
                'meta_description' => 'Scenic riverfront land parcel near Dharmadam Island walkway. Ideal for eco-resort or private farm villa.',
                'owner_name' => 'K. C. Balakrishnan',
                'owner_phone' => '+91 94472 66778',
                'owner_email' => 'kcbala@dharmadamfarms.in',
                'owner_notes' => 'Agricultural family estate.',
                'remark' => 'Tourist department project underway 1 km away which will appreciate capital value significantly.',
            ],
            [
                'title' => 'Contemporary 4BHK Architect Villa in Payyanur',
                'slug' => 'contemporary-4bhk-architect-villa-payyanur',
                'purpose' => 'sale',
                'type' => 'house',
                'price' => 17500000.00,
                'price_basis' => 'total',
                'negotiable' => true,
                'land_area' => 15.0,
                'land_area_unit' => 'cent',
                'building_area_sqft' => 3100.00,
                'bedrooms' => 4,
                'bathrooms' => 4,
                'amenities' => ['Home Cinema Room', 'Smart Home Automation', 'Solar Rooftop 5kW', 'EV Charging Point', 'Designer Kitchen'],
                'pros' => ['Brand new construction (2025 completion)', 'Zero water logging history', 'Energy positive house with net metering'],
                'cons' => ['Price is firm with minor room for negotiation'],
                'description' => 'Sleek cubist design showcasing exposed concrete textures, wooden louvers, and expansive glass panels that bathe the living spaces in natural light.',
                'locality' => 'Payyanur',
                'district' => 'Kannur',
                'address_line' => 'Near Perumba Junction, Payyanur 670307',
                'latitude' => 12.1000,
                'longitude' => 75.2000,
                'virtual_tour_url' => null,
                'rera_number' => 'K-RERA/PRJ/KAN/088/2024',
                'land_classification' => 'Residential',
                'status' => 'available',
                'is_published' => true,
                'is_featured' => false,
                'view_count' => 264,
                'meta_title' => 'Architect 4BHK Smart Villa on 15 Cents in Payyanur | KARMA',
                'meta_description' => 'Modern cubist 4BHK smart home in Payyanur with solar rooftop, EV charger, and cinema room.',
                'owner_name' => 'Ar. Vipin Chandran',
                'owner_phone' => '+91 98470 55112',
                'owner_email' => 'vipin@studioarch.in',
                'owner_notes' => 'Architect moving to Germany.',
                'remark' => 'Architect owner moving abroad. All furniture can be included for additional ₹12 Lakhs.',
            ],
            [
                'title' => 'Colonial Style Sea-Facing Bungalow in Thalassery',
                'slug' => 'colonial-sea-facing-bungalow-thalassery',
                'purpose' => 'sale',
                'type' => 'house',
                'price' => 39000000.00,
                'price_basis' => 'total',
                'negotiable' => true,
                'land_area' => 42.0,
                'land_area_unit' => 'cent',
                'building_area_sqft' => 4500.00,
                'bedrooms' => 6,
                'bathrooms' => 6,
                'amenities' => ['British Era High Ceilings', 'Granite Paved Driveway', 'Vintage Terracotta Tiles', 'Caretaker Cottage', 'Deep Sea Views'],
                'pros' => ['Historic legacy property close to Thalassery Fort and Pier', 'Huge 42 cents land parcel in heart of town'],
                'cons' => ['Heritage conservation guidelines apply on facade alterations'],
                'description' => 'Rare British-colonial era sea-view residence situated high on the Thalassery coastline. Features broad verandahs, ornate arches, and breezy high ceilings.',
                'locality' => 'Thalassery',
                'district' => 'Kannur',
                'address_line' => 'Fort Road, Near Sea View Park, Thalassery 670101',
                'latitude' => 11.7480,
                'longitude' => 75.4890,
                'virtual_tour_url' => null,
                'rera_number' => null,
                'land_classification' => 'Residential Purayidam',
                'status' => 'available',
                'is_published' => true,
                'is_featured' => false,
                'view_count' => 520,
                'meta_title' => 'Historic British Colonial Sea-Facing Bungalow in Thalassery | KARMA',
                'meta_description' => 'Rare 6BHK sea-view heritage residence on 42 cents near Thalassery Fort with deep ocean panoramas.',
                'owner_name' => 'Kuruvilla Thomas Family',
                'owner_phone' => '+91 94470 88123',
                'owner_email' => 'kuruvilla.thomas@heritagekerala.com',
                'owner_notes' => 'Prominent heritage family. Requires NDA before physical inspection.',
                'remark' => 'High profile seller. Strict non-disclosure requested before in-person site visit.',
            ],
            [
                'title' => 'Hillside Spices & Plantation Villa in Iritty',
                'slug' => 'hillside-spices-plantation-villa-iritty',
                'purpose' => 'sale',
                'type' => 'house',
                'price' => 21500000.00,
                'price_basis' => 'total',
                'negotiable' => true,
                'land_area' => 85.0,
                'land_area_unit' => 'cent',
                'building_area_sqft' => 3600.00,
                'bedrooms' => 4,
                'bathrooms' => 4,
                'amenities' => ['Rubber & Pepper Plantation', 'Mountain Stream Access', 'Private Well Water', 'Solar Power System', 'Fruit Trees Orchard'],
                'pros' => ['Lush scenic hill country climate in Iritty', 'High yield active rubber and black pepper harvest', 'Quiet retreat away from coastal humidity'],
                'cons' => ['25 km drive from Kannur city center'],
                'description' => 'Expansive 85-cent plantation estate nestled in the scenic green hills of Iritty. Features a contemporary 4BHK Kerala-style villa with mountain stream views.',
                'locality' => 'Iritty',
                'district' => 'Kannur',
                'address_line' => 'Payyavoor Road, Near Hill Highway, Iritty 670703',
                'latitude' => 11.9800,
                'longitude' => 75.6600,
                'virtual_tour_url' => null,
                'rera_number' => null,
                'land_classification' => 'Agricultural / Plantation Land',
                'status' => 'available',
                'is_published' => true,
                'is_featured' => true,
                'view_count' => 380,
                'meta_title' => '85 Cents Plantation Villa for Sale in Iritty, Kannur | KARMA',
                'meta_description' => 'Scenic 4BHK hill country villa on 85 cents in Iritty with rubber and pepper plantation.',
                'owner_name' => 'Joseph Varghese',
                'owner_phone' => '+91 94473 11445',
                'owner_email' => 'joseph.iritty@gmail.com',
                'owner_notes' => 'Planter family in Iritty.',
                'remark' => 'Clean title deeds. Yearly yield from rubber and spices covers maintenance.',
            ],
            [
                'title' => 'Marine Drive Waterfront Luxury Apartment in Kochi',
                'slug' => 'marine-drive-waterfront-luxury-apartment-kochi',
                'purpose' => 'sale',
                'type' => 'flat',
                'price' => 24500000.00,
                'price_basis' => 'total',
                'negotiable' => true,
                'land_area' => null,
                'land_area_unit' => 'sqft',
                'building_area_sqft' => 2800.00,
                'bedrooms' => 3,
                'bathrooms' => 4,
                'amenities' => ['Vembanad Backwater Sunset View', 'Private Boat Slip', 'Infinity Rooftop Pool', 'Concierge Service', '2 Covered Car Parks'],
                'pros' => ['Prestigious Marine Drive address in Ernakulam/Kochi', 'Uninterrupted backwater and harbor view'],
                'cons' => ['Monthly HOA maintenance ₹7,500'],
                'description' => 'Ultra-luxury 3BHK high-rise apartment overlooking the Arabian Sea backwaters at Marine Drive, Kochi. Designer Italian marble interiors and floor-to-ceiling glass walls.',
                'locality' => 'Marine Drive',
                'district' => 'Ernakulam',
                'address_line' => 'Skyline Waterfront, Marine Drive, Kochi 682031',
                'latitude' => 9.9816,
                'longitude' => 76.2753,
                'virtual_tour_url' => null,
                'rera_number' => 'K-RERA/PRJ/ERS/012/2023',
                'land_classification' => 'Residential Flat',
                'status' => 'available',
                'is_published' => true,
                'is_featured' => true,
                'view_count' => 640,
                'meta_title' => 'Luxury Waterfront 3BHK Flat Marine Drive Kochi | KARMA',
                'meta_description' => '2800 sq.ft luxury waterfront flat at Marine Drive Kochi with sea views and rooftop pool.',
                'owner_name' => 'Dr. Alexander Kurian',
                'owner_phone' => '+91 98460 12345',
                'owner_email' => 'alex.kurian@kochi-health.org',
                'owner_notes' => 'Senior Surgeon in Kochi.',
                'remark' => 'Prime investment property with steady NRI rental demand.',
            ],
            [
                'title' => 'Beachfront Luxury Penthouse in Kozhikode',
                'slug' => 'beachfront-luxury-penthouse-kozhikode',
                'purpose' => 'sale',
                'type' => 'flat',
                'price' => 18900000.00,
                'price_basis' => 'total',
                'negotiable' => true,
                'land_area' => null,
                'land_area_unit' => 'sqft',
                'building_area_sqft' => 2600.00,
                'bedrooms' => 3,
                'bathrooms' => 3,
                'amenities' => ['Panoramic Sea Deck', 'Private Elevator', 'Gymnasium', '24/7 Security'],
                'pros' => ['Direct sea view over Kozhikode Calicut beach', 'Walking distance to iconic food joints and pier'],
                'cons' => ['High demand area'],
                'description' => 'Stunning oceanfront penthouse on Calicut Beach Road. Broad glass terrace overlooking the Arabian Sea sunsets.',
                'locality' => 'Beach Road',
                'district' => 'Kozhikode',
                'address_line' => 'Ocean Crest Towers, Beach Road, Kozhikode 673032',
                'latitude' => 11.2588,
                'longitude' => 75.7804,
                'virtual_tour_url' => null,
                'rera_number' => 'K-RERA/PRJ/KKD/044/2023',
                'land_classification' => 'Residential Flat',
                'status' => 'available',
                'is_published' => true,
                'is_featured' => true,
                'view_count' => 490,
                'meta_title' => '3BHK Oceanfront Penthouse Kozhikode Beach | KARMA',
                'meta_description' => '2600 sq.ft sea deck penthouse on Kozhikode Beach Road.',
                'owner_name' => 'Firoz K. P.',
                'owner_phone' => '+91 94470 54321',
                'owner_email' => 'firoz.kp@calicuttraders.com',
                'owner_notes' => 'Kozhikode business owner.',
                'remark' => 'Clear title deed.',
            ],
            [
                'title' => 'Wayanad Hilltop Tea Estate Eco Villa in Vythiri',
                'slug' => 'wayanad-hilltop-tea-estate-eco-villa-vythiri',
                'purpose' => 'sale',
                'type' => 'house',
                'price' => 29500000.00,
                'price_basis' => 'total',
                'negotiable' => true,
                'land_area' => 120.0,
                'land_area_unit' => 'cent',
                'building_area_sqft' => 4100.00,
                'bedrooms' => 5,
                'bathrooms' => 5,
                'amenities' => ['Tea Plantation Frontage', 'Mist & Cloud Canopy', 'Fireplace Living Room', 'Boutique Resort Permit'],
                'pros' => ['Cool year-round hill station climate (18°C-24°C)', 'High weekend homestay income potential'],
                'cons' => ['Requires monsoon slope inspection'],
                'description' => 'Breathtaking 1.2-acre tea estate villa high in the mist-shrouded hills of Vythiri, Wayanad. Built with teak timber and natural stone.',
                'locality' => 'Vythiri',
                'district' => 'Wayanad',
                'address_line' => 'Lakkidi View Point Road, Vythiri, Wayanad 673576',
                'latitude' => 11.5528,
                'longitude' => 76.0410,
                'virtual_tour_url' => null,
                'rera_number' => null,
                'land_classification' => 'Agricultural / Resort Land',
                'status' => 'available',
                'is_published' => true,
                'is_featured' => true,
                'view_count' => 510,
                'meta_title' => '1.2 Acre Tea Estate Eco Villa in Vythiri, Wayanad | KARMA',
                'meta_description' => '5BHK luxury tea plantation villa in Vythiri Wayanad with mist views.',
                'owner_name' => 'Siddharth Roy',
                'owner_phone' => '+91 98950 99887',
                'owner_email' => 'siddharth@wayanadteahomes.com',
                'owner_notes' => 'Planter family.',
                'remark' => 'Boutique homestay license active.',
            ]
        ];

        $propertyImages = [
            'hillside-spices-plantation-villa-iritty' => [
                'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
            ],
            'marine-drive-waterfront-luxury-apartment-kochi' => [
                'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
            ],
            'beachfront-luxury-penthouse-kozhikode' => [
                'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
            ],
            'wayanad-hilltop-tea-estate-eco-villa-vythiri' => [
                'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80',
            ],
            'cliffside-beachfront-estate-thottada' => [
                'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
            ],
            'prime-commercial-corner-plot-talap' => [
                'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1524813686514-a57563d77d66?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=1200&q=80',
            ],
            'skyline-view-3bhk-penthouse-pallikkunnu' => [
                'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
            ],
            'airport-logistics-warehouse-mattannur' => [
                'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=1200&q=80',
            ],
            'heritage-nalukettu-villa-taliparamba' => [
                'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80',
            ],
            'gated-community-residential-plot-chalad' => [
                'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80',
            ],
            'national-highway-commercial-showroom-chovva' => [
                'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80',
            ],
            'coconut-grove-island-plot-dharmadam' => [
                'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
            ],
            'contemporary-4bhk-architect-villa-payyanur' => [
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
            ],
            'colonial-sea-facing-bungalow-thalassery' => [
                'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=1200&q=80',
            ],
        ];

        foreach ($properties as $item) {
            $remark = $item['remark'];
            unset($item['remark']);

            $property = Property::updateOrCreate(['slug' => $item['slug']], $item);

            InternalRemark::updateOrCreate(
                ['property_id' => $property->id],
                ['remark' => $remark]
            );

            $imgs = $propertyImages[$property->slug] ?? [];
            if (! empty($imgs)) {
                // Remove existing media to avoid duplicate cover conflicts
                PropertyMedia::where('property_id', $property->id)->delete();
                foreach ($imgs as $idx => $imgUrl) {
                    PropertyMedia::create([
                        'property_id' => $property->id,
                        'media_type' => 'photo',
                        'thumb_path' => $imgUrl,
                        'medium_path' => $imgUrl,
                        'full_path' => $imgUrl,
                        'is_cover' => $idx === 0,
                        'sort_order' => $idx,
                    ]);
                }
            }
        }
    }
}

